### ISSUE TITLE
你好，使用AS的gradle Task编译出来的hide-toll.jar为何不包含它的依赖com.alibaba.fastjson呢

### ISSUE THREAD

**Issue by HuTianQi** [gnaixx/hidex-hack#4]
Exception in thread "main" java.lang.NoClassDefFoundError: com/alibaba/fastjson/
JSONObject
        at cc.gnaixx.tools.model.dex.DexFile.toJsonStr(DexFile.java:64)
        at cc.gnaixx.tools.core.HidexHandle.hidex(HidexHandle.java:51)
        at cc.gnaixx.tools.core.Main.hidex(Main.java:86)
        at cc.gnaixx.tools.core.Main.main(Main.java:70)
Caused by: java.lang.ClassNotFoundException: com.alibaba.fastjson.JSONObject
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

**Comment by gnaixx** [comment]
如果你想把依赖打进到导出的jar 中需要使用fat-jar。我目前是把到copy到导出的libs 目录下。https://github.com/gnaixx/hidex-hack/blob/ab35ff445db591224565b085a766e0fbe044dab2/hidex.sh#L33
